# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
      - sourceline: 'pbs-assess/rosettafish'
    packages:
      - libmagick++-dev

after_success:
    - Rscript -e 'covr::codecov()'
