# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/imagemagick'
    - sourceline: 'ppa:ubuntugis/poppler'
    packages:
    - libmagick++-dev
    - libpoppler-cpp-dev

after_success:
    - Rscript -e 'covr::codecov()'
